test:
  variables:
    TEST_DATABASE_URL: postgres://postgres:sermo@sermo-postgres:5432
  script:
    - npm ci
    - npm ci --prefix duco-client
    - npm run lint
    - npm run format -- --check
    - npm run test duco-server/src -- --runInBand
    - npm run test duco-server/test -- --runInBand --testTimeout=10000
    - CI=false npm run build
  tags:
    - sermo
    - node
  only:
    - merge_requests
    - master
